#!/usr/bin/env ruby

require 'bitbucket_snagger'
require 'escort'

Escort::App.create do |app|
  app.version "0.0.1"
  app.summary "bitbucket_snagger"
  app.description "Snag git repos and upload them to bitbucket :D"

  app.options do |opts|
    opts.opt :username,
      'BitBucket username',
      :long => '--username',
      :type => :string

      opts.opt :password,
        'BitBucket password',
        :long => '--password',
        :type => :string

      opts.opt :base_url,
        'Base URL to access bitbucket, eg https://code.megacorp.com/scm',
        :long => '--base-url',
        :type => :string

      opts.opt :project,
        'BitBucket project name',
        :long => '--project',
        :type => :string

      opts.opt :repo,
        'BitBucket repo name',
        :long => '--repo',
        :type => :string

      opts.opt :upstream,
        'Upstream repo URL',
        :long => '--upstream',
        :type => :string

  end

  app.command :snag do |command|
    command.summary "snag a module"
    command.description "create a repo if needed and sync it to upstream"
    command.action do |options, arguments|
      begin
        BitbucketSnagger::BitbucketSnagger.new(options, arguments).sync_repo()
      rescue BitBucket::Error::Unauthorized => e
        Escort::Logger.output.puts "BitBucket authentication error! (#{e.message})"
      end
    end
  end
end
