#!/usr/bin/env ruby

require 'bitbucket_snagger'
require 'escort'

Escort::App.create do |app|
  app.version "0.0.1"
  app.summary "bitbucket_snagger"
  app.description "Snag git repos and upload them to bitbucket :D"

  app.options do |opts|
      opts.opt :projectKey,
        'BitBucket projectKey.  Not to be confused with the project name, eg puppet project often has a project key "pup"',
        :long => '--projectKey',
        :type => :string

      opts.opt :repositorySlug,
        'BitBucket repo name',
        :long => '--repositorySlug',
        :type => :string

      opts.opt :upstream,
        'Upstream repo URL',
        :long => '--upstream',
        :type => :string
  end

  app.command :snag do |command|
    command.summary "snag a module"
    command.description "create a repo if needed and sync it to upstream"
    command.action do |options, arguments|
      BitbucketSnagger::BitbucketSnagger.new(options, arguments).sync_repo()
    end
  end

  app.command :logout do |command|
    command.summary "logout"
    command.description "remove credentials from ~/.bitbucket_snagger.ini"
    command.action do |options, arguments|
      BitbucketSnagger::BitbucketSnagger.new(options, arguments).logout()
    end
  end
end
